import Head from "next/head";
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta
          name="Facebook clone by next js"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>New project</h1>
      {/* header */}
      <main>
        {/* Sidebar left */}
        {/* Feeds middle -section- */}
        {/* widgets - right section- */}
      </main>
    </div>
  );
}
