import { getSession } from "next-auth/client";
import Head from "next/head";
import Header from "../components/Header";
import Login from "../components/Login";

// import styles from '../styles/Home.module.css'

export default function Home({ session }) {
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta
          name="Facebook clone by next js"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>

      <main>
        {/* Sidebar -left section */}
        {/* Feeds middle -section- */}
        {/* widgets -right section- */}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  // get the user
  const session = await getSession(context)
  return {
    props: {
  session
}
  }
}